pr:
  branches:
    include:
      - master
      - feature/*
      - release/*
      - hotfix/*

jobs:
  - template: eng/build-job.yaml
    parameters:
      ArtifactName: 'packages'
      ProfileFlag: '-Djava-lts'
      JavaVersion: '1.11'
  - template: eng/test-job.yaml